openapi: 3.0.1
info:
  title: Chotuve Media Server API Rest documentation
  description: Chotuve Media Server API REST documentation
  termsOfService: https://fiuba-taller-2-media-server.herokuapp.com/
  contact:
    email: grupo8@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 2.0.0
tags:
- name: Ping
  description: A simple ping
- name: Ping
paths:
  /ping:
    get:
      tags:
      - Ping
      summary: Make a ping
      description: Make a ping
      responses:
        200:
          description: Ping ok
          content:
            text/plain:
              schema:
                type: string
                example: pong
