openapi: "3.0.0"
info:
  title: Simple API overview
  version: 2.0.0
paths:
  /ping:
    get:
      responses:
        '200':
          description: A User object
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                  avatar:          # <-- image embedded into JSON
                    type: string
                    format: byte
                    description: Base64-encoded contents of the avatar image